https://github.com/uzochukwueddie/react-calendar-app
https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Ffullcalendar.io%2Fdocs%2Fbootstrap-theme-demo

FULL: PREMIUM DOWNLOAD https://github.com/fullcalendar/fullcalendar-scheduler

https://www.udemy.com/course/the-react-developer-course-with-hooks-context-api-and-redux/learn/lecture/18087431#overview


In Downloads Directory
Downloads/react-calendar-app-master.zip

https://github.com/bradtraversy/contact-keeper
https://github.com/bradtraversy/contact_keeper_api